dist: xenial
sudo: required

language: c
script: true

addons:
  apt:
    packages:
      - cpanminus
      - build-essential
      - libncurses5-dev
      - libreadline-dev
      - libssl-dev
      - perl
      - etcd
      - wrk

before_install:
  - ls -la ./bin
  - ./bin/travis-runner.sh before_install

install:
  - ./bin/travis-runner.sh do_install

script:
  - ./bin/travis-runner.sh script

after_success:
  - ./bin/travis-runner.sh after_success
